[[main]]
  identifier = "Dokumentation"
  name = "Dokumentation"
  url = "documentation"
  weight = 1

[[main]]
  identifier = "Support"
  name = "Support"
  url = "support"
  weight = 2

[[main]]
  identifier = "BELWARE"
  name = "BELWARE"
  url = "https://belware.de"
  weight = 3

[[main]]
  identifier = "Impressum"
  name = "Impressum"
  url = "legalnotice"
  weight = 4

