[[main]]
  identifier = "Connector 365"
  name = "Connector 365"
  url = "connector365"
  weight = 1

[[main]]
  identifier = "Impressum"
  name = "Impressum"
  url = "impressum"
  weight = 2

[[main]]
  identifier = "BELWARE"
  name = "BELWARE"
  url = "https://belware.de"
  weight = 3