[[main]]
  identifier = "Documentation"
  name = "Documentation"
  url = "documentation"
  weight = 1

[[main]]
  identifier = "Support"
  name = "Support"
  url = "support"
  weight = 2

[[main]]
  identifier = "BELWARE"
  name = "BELWARE"
  url = "https://belware.de"
  weight = 3

[[main]]
  identifier = "Legal Notice"
  name = "Legal Notice"
  url = "legalnotice"
  weight = 4

